name: Build Docker Image

on:
  workflow_run:
    workflows: ["Install Apache"]
    types:
      - completed

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-apache-image .

      - name: Run Docker container
        run: |
          docker run -d -p 80:80 my-apache-image

      - name: Verify Docker container
        run: |
          sleep 10
          curl -v http://localhost:80